base: &base
    working_directory: ~/php-oauth
    docker:
        - image: cimg/php:8.4

remote-docker: &remote_docker
    setup_remote_docker

docker-info: &docker_info
    run: docker info

version: 2
jobs:
    build-php81:
        <<: *base
        steps:
            - checkout
            - *remote_docker
            - *docker_info
            -   run: docker build --build-arg PHP_VERSION=8.1 -t tests-php81 .
            -   run: docker run tests-php81

    build-php82:
        <<: *base
        steps:
            - checkout
            - *remote_docker
            - *docker_info
            -   run: docker build --build-arg PHP_VERSION=8.2 -t tests-php82 .
            -   run: docker run tests-php82

    build-php83:
        <<: *base
        steps:
            - checkout
            - *remote_docker
            - *docker_info
            -   run: docker build --build-arg PHP_VERSION=8.3 -t tests-php83 .
            -   run: docker run tests-php83

    build-php84:
        <<: *base
        steps:
            - checkout
            - *remote_docker
            - *docker_info
            -   run: docker build --build-arg PHP_VERSION=8.4 -t tests-php84 .
            -   run: docker run tests-php84

workflows:
    version: 2
    all:
        jobs:
            - build-php81
            - build-php82
            - build-php83
            - build-php84
